### DISCUSSION TITLE
How to prevent code blocks from displaying syntax tags ?

### DISCUSSION THREAD

**Discussion by nibazshab** [vuepress/core#1150] [Q&A] [answered]
see it, how need i do can prevent it show ?

![image](https://user-images.githubusercontent.com/44338441/198826080-b470491c-6db1-45ca-ac96-165d81a4cd33.png)

**Comment by Mister-Hope** [comment, marked as answer]
Add this in your `index.scss`

```css
div[class*='language-']::before {
  display: none;
}
```

If  you only want to hide some extension, (e.g.: hide sh)


```css
div[class*='language-' data-ext='sh']::before {
  display: none;
}
```
