### DISCUSSION TITLE
How can I make the middle content a little wider, the default width is very unfriendly for table display.

### DISCUSSION THREAD

**Discussion by MoonLord-LM** [vuepress/core#1157] [Q&A] [answered]
How can I make the middle content a little wider, the default width is very unfriendly for table display.
怎样让正文的内容更宽一点，默认的宽度对于表格显示很不友好

**Comment by Mister-Hope** [comment, marked as answer]
Replace `100000000000000000000px` with values you like.

```css
#app {
  --content-width: 100000000000000000000px;
}
```
