### DISCUSSION TITLE
Use github action to deploy vuepress but an error was reported

### DISCUSSION THREAD

**Discussion by haihouch** [vuepress/core#1341] [Q&A] [answered]
I used the github deployment template for vuepress2.0,

```
name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 7
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: 18
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: page
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.VUE_TOKEN }}

```

`.github.workflows.docs.yml` I barely changed anything,

github action will send error in `Setup pnpm` before I delete `^` of  '"vuepress": "2.0.0-beta.62" `in package.json

Now I have a new problem
```
Error: [vite]: Rollup failed to resolve import "vue" from "/home/runner/work/chang144.github.io/chang144.github.io/node_modules/.pnpm/@vuepress+client@2.0.0-beta.62/node_modules/@vuepress/client/dist/app.js".
```

https://github.com/chang144/chang144.github.io/actions/runs/5077037977/jobs/9119837076

I tried to add the following file to solve the problem, but it still didn't work

```
import alias from "@rollup/plugin-alias";
import {resolve} from 'path'
import {defineConfig} from 'vite'
export default defineConfig({
    plugins: [alias()],
    resolve: {
        alias: {
            "/@": resolve(__dirname, "./src"),
        },
    },
})
```
