### DISCUSSION TITLE
How to increase content for specify page

### DISCUSSION THREAD

**Discussion by zenkiet** [vuepress/core#409] [Q&A] [answered]
I found code after the image affects the width of the content

```css
.theme-default-content:not(.custom) {
    max-width: var(--content-width);
    margin: 0 auto;
    padding: 2rem 2.5rem;
}
```

with: --content-width = 740px

i want to increase it to 1000, but it only works some pages, the rest is as usual

Thank You!!!
